### ISSUE TITLE
Research testing options for meteor package-based app architecture

### ISSUE THREAD

**Issue by aslagle** [ecohealthalliance/mantle#5]

**Comment by nathanathan** [comment]
As far as I can tell the Jasmine package is the only velocity package offering package level testing. I experimented with it on this branch: https://github.com/ecohealthalliance/rana/tree/experimental-unit-testing
I haven't been able to make package tests work on our rana:groups package, although they work in simple packages like this one: https://github.com/ecohealthalliance/rana/tree/experimental-unit-testing/packages/package-to-test
When [certain packages are used](https://github.com/ecohealthalliance/rana/blob/experimental-unit-testing/packages/package-to-test/package.js#L22) some of the tests will freeze. When I tried adding a test to the groups package I encountered this error:
```
failed to subscribe to VelocityMirrors subscription { [Error: Subscription not found [404]]
error: 404,
reason: 'Subscription not found',
details: undefined,
message: 'Subscription not found [404]',
errorType: 'Meteor.Error' }
```

We can unit test packages in the application tests like this without errors:
https://github.com/ecohealthalliance/rana/blob/experimental-unit-testing/tests/jasmine/client/unit/sample/spec/spec.coffee
One advantage of this approach is that the results show up in velocity html-reports. However, the tests are not as encapsulated (we could mitigate that by using mocks), and if we didn't want the tests to run on every change we would have to add extra parameters to disable them.

I was able to make Travis CI work with both types of tests using the meteor-jasmine sample-app:
https://github.com/nathanathan/meteor-jasmine/pull/1/files

**Comment by dannysullivan** [comment]
I just spent some time messing with these options as well and also couldn't get that jasmine package working.  My main issue with writing the tests at the application level, rather than the package level, is that the packages wouldn't be entirely self-contained or transferrable to other contexts (i.e., if we or someone else use the packages in another app we lose the test coverage).  Let me know if I'm wrong about that or missing something about Meteor.

It seems like Tinytest has some support for unit testing within a package: https://www.eventedmind.com/feed/meteor-testing-packages-with-tinytest.  Is there a reason we shouldn't use this?  I was able to get a few basic tests running this way.

I'd love to find a solution to this but I don't get the impression that most of the Meteor community is unit testing on the package level at the moment.

**Comment by aslagle** [comment]
Tinytest is definitely an option, I've used it for testing packages and liked it much better than velocity. It can be a little awkward to use it for things like UI testing and we'll have to write a lot more support code than if we used another framework. Velocity might also have more advantages like parallelization in the future.

**Comment by dannysullivan** [comment]
I was thinking Tinytest for unit tests on the package level and then something bigger for integration tests and most of the interface stuff, though I haven't quite wrapped my head around the package structure yet so I'm not sure that it makes sense to split the interface out from the package like that.  Do you think most of our testing is going to be contained within individual packages? Or will it be more like the tests in rana, most of which touched a few parts of the application?

**Comment by aslagle** [comment]
I'd prefer to put much more in the packages, but I'm not sure it will be possible.

**Comment by dannysullivan** [comment]
@nathanathan, looks like that subscription error has to do with the specific version of sanjo:jasmine we were trying to use. If you put "api.use('sanjo:jasmine@0.13.3');" in package's onTest everything seems to work.  I'll try and set up a basic testing file structure for accounts stuff now (even though there isn't really logic to test yet, I think it's useful to have a pattern in place as early as possible).

**Comment by dannysullivan** [comment]
Check out https://github.com/ecohealthalliance/mantle/pull/43 for the basic stuff I set up - it's a branch off this branch and should be easy to merge if you all are cool with doing things this way.
