### ISSUE TITLE
Include mantle tests in TravisCI testing

### ISSUE THREAD

**Issue by frosario** [ecohealthalliance/mantle#52]

**Comment by frosario** [comment]
@aslagle I remember a few weeks ago we worked on the travisCI branch to get our tests into CI. Is there a newer branch with more updated tests I can merge? IIRC we decided to try out tinytest?

**Comment by aslagle** [comment]
The new tests are on master now so you can start a new branch from there.

**Comment by aslagle** [comment]
testing info here: https://github.com/ecohealthalliance/mantle/wiki/Testing

**Comment by frosario** [comment]
New PR sets up testing on newer container based travisCI environment.
https://github.com/ecohealthalliance/mantle/pull/56
